package com.tweetarchive.main.model.enums;

public enum ErrorCode {
    COLLECTION_ALREADY_LIKED,
    COLLECTION_NOT_FOUND,
    USER_NOT_FOUND,
    INVALID_REQUEST,
    EMAIL_ALREADY_EXISTS, TWEET_DOESNT_EXIST,
    TWEET_NOT_BELONG_THIS_COLLECTION,
    COLLECTION_NOT_LIKED, AUTHENTICATED_ERROR, INVALID_URL
}